version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/London"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:00"
      timezone: "Europe/London"
