version: "3"
services:
  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/auth/health"]
    environment:
      - SERVER_PORT=8090
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL=false

  assess-risks-and-needs:
    image: quay.io/hmpps/hmpps-assess-risks-and-needs:latest
    networks:
      - hmpps
    container_name: assess-risks-and-needs
    ports:
      - "8094:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - OAUTH_ENDPOINT_URL=http://hmpps-auth:8090/auth

  postgres:
    image: postgres:14.7-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./src/main/resources/db/local/init:/docker-entrypoint-initdb.d:ro

networks:
  hmpps:
