notify:
  enabled: false

interventions-ui:
  baseurl: http://localhost:3000

community-api:
  baseUrl: http://localhost:8081
#  Temporarily stored in config until it is decided where these values will come from. TeamCode may come from the community api
#  in the future. The rest may be hard coded as generic values.
  contactNotificationContext:
    probationAreaCode: A00
    referralType: C385
    staffCode: ASPUATU
    teamCode: ASPUAT

aws:
  sns:
    enabled: false
    provider: localstack
    access-key-id: test
    secret-access-key: test
    endpoint.uri: http://localhost:4566
    topic.arn: arn:aws:sns:eu-west-2:000000000000:intervention-events-local

hmppsauth:
  baseurl: http://hmpps-auth:8090/auth

postgres:
  uri: localhost:5432
  db: interventions
  username: postgres
  password: password

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  flyway:
    locations: classpath:db/migration,classpath:db/local
  security:
    oauth2:
      client:
        registration:
          community-api:
            client-id: interventions
            client-secret: clientsecret
