notify:
  enabled: false

interventions-ui:
  baseurl: http://localhost:3000

interventions-api:
  baseurl: http://localhost:8080

refer-and-monitor-and-delius:
  baseurl: http://localhost:9090

community-api:
  baseurl: http://localhost:8091
  referrals:
    enabled: false
  appointments:
    bookings:
      enabled: false
    outcome:
      enabled: false

prisoner-offender-search:
  baseurl: http://localhost:9092

assess-risks-and-needs:
  baseurl: http://localhost:8094

aws:
  s3:
    storage:
      enabled: false
      access-key-id: test
      secret-access-key: test
      endpoint.uri: http://localhost:4566
      bucket.name: interventions-bucket-local
    ndmis:
      enabled: false
      access-key-id: test
      secret-access-key: test
      endpoint.uri: http://localhost:4566
      bucket.name: interventions-bucket-ndmis
  sns:
    enabled: false
    provider: localstack
    access-key-id: test
    secret-access-key: test
    endpoint.uri: http://localhost:4566
    topic.arn: arn:aws:sns:eu-west-2:000000000000:intervention-events-local

hmppsauth:
  baseurl: http://hmpps-auth:8090/auth

postgres:
  uri: localhost:5432
  db: interventions
  username: postgres
  password: password

spring:
  main:
    banner-mode: console
  security:
    oauth2:
      client:
        registration:
          interventions-client:
            client-id: interventions
            client-secret: clientsecret

azure.application-insights.instrumentation-key: dummy
