notify:
  enabled: false

interventions-ui:
  baseurl: http://localhost:3000

hmppsauth:
  baseurl: http://hmpps-auth:8090/auth

postgres:
  uri: localhost:5432
  db: interventions
  username: postgres
  password: password

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  flyway:
    locations: classpath:db/migration,classpath:db/local
