hmppsauth:
  baseurl: http://hmpps-auth:8090/auth

postgres:
  uri: localhost:5432
  db: interventions
  username: postgres
  password: password

logging:
  level:
    org:
      springframework:
        security: DEBUG
      flywaydb: DEBUG

spring:
  flyway:
    locations: classpath:db/migration,classpath:db/local
    clean-on-validation-error: true # DO NOT *EVER* SET THIS IN PRODUCTION
