version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@2.1.0
  snyk: snyk/snyk@0.0.12

_snyk_options: &snyk_options
  snyk-scan: true
  snyk-fail-build: true
  snyk-args: --policy-path=.snyk --configuration-matching='^((?!test).)*$'

jobs:
  validate:
    executor: hmpps/java
    docker:
      - image: cimg/openjdk:11.0
        environment:
          POSTGRES_DB: circle_test
      - image: circleci/postgres:10-alpine-ram
        environment:
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

  pact_check_and_publish:
    environment:
      PACT_BROKER_HOST: "pact-broker-prod.apps.live-1.cloud-platform.service.justice.gov.uk"
      PACT_BROKER_USERNAME: "interventions"
    executor: hmpps/java
    docker:
      - image: cimg/openjdk:11.0
        environment:
          POSTGRES_DB: circle_test
      - image: circleci/postgres:10-alpine-ram
        environment:
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: |
            PACT_PROVIDER_VERSION="$CIRCLE_SHA1" \
              PACT_PROVIDER_TAG="$CIRCLE_BRANCH" \
              ./gradlew pactTestPublish
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}

  vulnerability_scan:
    executor: hmpps/java
    parameters:
      monitor:
        type: boolean
        default: false
      snyk-scan:
        type: boolean
      snyk-fail-build:
        type: boolean
      snyk-args:
        type: string
    steps:
      - checkout
      - snyk/scan:
          project: '${CIRCLE_PROJECT_REPONAME}'
          monitor-on-build: << parameters.monitor >>
          organization: "digital-probation-services"
          severity-threshold: "high" # note: this does not affect snyk 'monitor' commands
          fail-on-issues: << parameters.snyk-fail-build >>
          additional-arguments: << parameters.snyk-args >>


workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - validate
      - pact_check_and_publish
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_and_publish_docker
          <<: *snyk_options
          filters:
            branches:
              only:
                - main
      - vulnerability_scan:
          name: vulnerability_scan_and_monitor
          monitor: true
          <<: *snyk_options
          filters:
            branches:
              only:
                - main
      - vulnerability_scan:
          <<: *snyk_options
          filters:
            branches:
              ignore:
                - main
      - hmpps/build_docker:
          name: build_docker
          publish: false
          <<: *snyk_options
          filters:
            branches:
              ignore:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          retrieve_secrets: "none"
          slack_notification: true
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - pact_check_and_publish
            - build_and_publish_docker
            - helm_lint
            - vulnerability_scan_and_monitor

  nightly:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - vulnerability_scan:
          name: vulnerability_scan_and_monitor
          monitor: true
          <<: *snyk_options
      - hmpps/build_docker:
          publish: false
          <<: *snyk_options
