version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@1.1.3
  snyk: snyk/snyk@0.0.12

jobs:
  validate:
    executor: hmpps/java
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

  vulnerability_scan:
    executor: hmpps/java
    parameters:
      monitor:
        type: boolean
        default: false
    steps:
      - checkout
      - snyk/scan:
          project: '${CIRCLE_PROJECT_REPONAME}'
          monitor-on-build: << parameters.monitor >>
          organization: "digital-probation-services"
          severity-threshold: "high" # note: this does not affect snyk 'monitor' commands
          fail-on-issues: true

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_and_publish_docker
          snyk-scan: false # fixme!
          filters:
            branches:
              only:
                - main
      - vulnerability_scan:
          name: vulnerability_scan_and_monitor
          monitor: true
          filters:
            branches:
              only:
                - main
      - vulnerability_scan:
          filters:
            branches:
              ignore:
                - main
      - hmpps/build_docker:
          name: build_docker
          publish: false
          snyk-scan: false # fixme!
          filters:
            branches:
              ignore:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          retrieve_secrets: "none"
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_and_publish_docker
            - helm_lint

  nightly:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - vulnerability_scan:
          name: vulnerability_scan_and_monitor
          monitor: true
      - hmpps/build_docker:
          publish: false
          snyk-scan: true
