{
 "title": "HMPPS Refer and monitor an intervention",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{namespace='$namespace',container!=\"POD\",container!=\"\"}) by (container)",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='$namespace'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='$namespace'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "Dashboard request durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le)(\n  increase(\n    nginx_ingress_controller_request_duration_seconds_bucket{\n      exported_namespace =~ \"$namespace\",\n      exported_service = \"hmpps-interventions-service-dashboard\",\n    }[1m]\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (container)(rate(container_cpu_usage_seconds_total{namespace='$namespace',container!=\"POD\",container!=\"\"}[5m]))",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace='$namespace'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace='$namespace'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "UI request durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le)(\n  increase(\n    nginx_ingress_controller_request_duration_seconds_bucket{\n      exported_namespace =~ \"$namespace\",\n      exported_service = \"hmpps-interventions-ui\",\n    }[1m]\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Production database CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-e4573fa1c83bbbb9"
     },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Service request durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (le)(\n  increase(\n    nginx_ingress_controller_request_duration_seconds_bucket{\n      exported_namespace =~ \"$namespace\",\n      exported_service = \"hmpps-interventions-service-api\",\n    }[1m]\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Garbage collection time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (container)(300*rate(jvm_gc_pause_seconds_sum{namespace='$namespace'}[5m]))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Dependency call times (from API, 99th percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.99, 300*rate(http_client_requests_seconds_sum{namespace='$namespace'}[5m])) by (client_name)",
     "legendFormat": "{{ client_name }}"
    }
   ]
  },
  {
   "title": "Longest API requests (99th percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, quantile(0.99, 300*rate(http_server_requests_seconds_sum{namespace='$namespace'}[5m])) by (uri))",
     "legendFormat": "{{ uri }}"
    }
   ]
  },
  {
   "title": "Dependency call times (from API, 100th percentile, worst calls)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(1, 300*rate(http_client_requests_seconds_sum{namespace='$namespace'}[5m])) by (client_name)",
     "legendFormat": "{{ client_name }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_receive_bytes_total{namespace='$namespace'}[5m]))))",
     "legendFormat": "Recv"
    },
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace='$namespace'}[5m]))))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "4xx responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_requests{status=~\"4..\",exported_namespace=\"$namespace\"}[1m])*60) by(exported_service,status)",
     "legendFormat": "{{exported_service}}@{{ status }}"
    }
   ]
  },
  {
   "title": "5xx responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_requests{status=~\"5..\",exported_namespace=\"$namespace\"}[1m])*60) by(exported_service,status)",
     "legendFormat": "{{exported_service}}@{{ status }}"
    }
   ]
  },
  {
   "title": "WAF (423)  responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_requests{status=~\"423\",exported_namespace=\"$namespace\"}[1m])*60) by(exported_service,status)",
     "legendFormat": "{{exported_service}}@{{ status }}"
    }
   ]
  },
  {
   "title": "2xx, 3xx responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_requests{status=~\"2..|3..\",exported_namespace=\"$namespace\"}[1m])*60) by(exported_service,status)",
     "legendFormat": "{{exported_service}}@{{ status }}"
    }
   ]
  },
  {
   "title": "Aborted (499) request durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum by (le)(\n  increase(\n    nginx_ingress_controller_request_duration_seconds_bucket{\n      status = \"499\",\n      exported_namespace =~ \"$namespace\"\n    }[1m]\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}