# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

nameOverride: hmpps-interventions-service

image:
  repository: ghcr.io/ministryofjustice/hmpps-interventions-service
  tag: latest
  ports:
    app: 8080
    dataDictionary: 8080

ingress:
  hosts:
    - host: hmpps-interventions-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk
  migration:
    colour: green

env_details:
  contains_live_data: false
  migrate_change_log: true

env:
  HMPPSAUTH_BASEURL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
  MANAGEUSERS_BASEURL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
  INTERVENTIONSUI_BASEURL: "https://hmpps-interventions-ui-dev.apps.live-1.cloud-platform.service.justice.gov.uk"
  COMMUNITYAPI_BASEURL: "https://community-api-secure.test.delius.probation.hmpps.dsd.io"
  REFERANDMONITORANDDELIUS_BASEURL: "https://refer-and-monitor-and-delius-dev.hmpps.service.justice.gov.uk"
  COMMUNITYAPI_APPOINTMENTS_OUTCOME_ENABLED: "true"
  ASSESSRISKSANDNEEDS_BASEURL: "https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk"
  PRISONEROFFENDERSEARCH_BASEURL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
  SENTRY_ENVIRONMENT: "dev"
  AWS_S3_STORAGE_ENABLED: "true"
  AWS_S3_NDMIS_ENABLED: "true"
  LOGGING_LEVEL_UK_GOV_JUSTICE_DIGITAL_HMPPS_HMPPSINTERVENTIONSSERVICE: "debug"
  OVERRIDES_SHOWFUTUREINTERVENTIONS: "true"
  ENVIRONMENT_NAME: DEV
