# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/hmpps-interventions-service
  tag: latest
  ports:
    app: 8080
    dataDictionary: 8080

ingress:
  enabled: true
  hosts:
    - host: hmpps-interventions-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk

env_details:
  contains_live_data: false

env:
  JAVA_OPTS: "-Xmx512m"
  HMPPSAUTH_BASEURL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
  INTERVENTIONSUI_BASEURL: "https://hmpps-interventions-ui-dev.apps.live-1.cloud-platform.service.justice.gov.uk"
  COMMUNITYAPI_BASEURL: "https://community-api-secure.test.delius.probation.hmpps.dsd.io"
  SENTRY_ENVIRONMENT: "dev"
