# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/hmpps-interventions-service
  tag: latest
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: hmpps-interventions-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
  HMPPSAUTH_BASEURL: "https://sign-in-dev.hmpps.service.justice.gov.uk"
  INTERVENTIONSUI_BASEURL: "https://hmpps-interventions-ui-dev.apps.live-1.cloud-platform.service.justice.gov.uk"
  COMMUNITYAPI_BASEURL: "https://community-api-secure.test.delius.probation.hmpps.dsd.io"
  COMMUNITYAPI_CONTACTNOTIFICATIONCONTEXT_PROBATIONAREACODE: "A00"
  COMMUNITYAPI_CONTACTNOTIFICATIONCONTEXT_REFERRALTYPE: "C385"
  COMMUNITYAPI_CONTACTNOTIFICATIONCONTEXT_STAFFCODE: "ASPUATU"
  COMMUNITYAPI_CONTACTNOTIFICATIONCONTEXT_TEAMCODE: "ASPUAT"
