# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/hmpps-interventions-service
  tag: latest
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: hmpps-interventions-service-preprod.hmpps.service.justice.gov.uk
      cert_secret: hmpps-interventions-service-cert
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
