# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

nameOverride: hmpps-interventions-service

image:
  repository: quay.io/hmpps/hmpps-interventions-service
  tag: latest
  ports:
    app: 8080
    dataDictionary: 8080

ingress:
  hosts:
    - host: hmpps-interventions-service-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
  migration:
    colour: green

env_details:
  contains_live_data: true
  migrate_change_log: true

env:
  HMPPSAUTH_BASEURL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
  MANAGEUSERS_BASEURL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
  INTERVENTIONSUI_BASEURL: "https://hmpps-interventions-ui-preprod.apps.live-1.cloud-platform.service.justice.gov.uk"
  COMMUNITYAPI_BASEURL: "https://community-api-secure.pre-prod.delius.probation.hmpps.dsd.io"
  REFERANDMONITORANDDELIUS_BASEURL: "https://refer-and-monitor-and-delius-preprod.hmpps.service.justice.gov.uk"
  COMMUNITYAPI_APPOINTMENTS_OUTCOME_ENABLED: "true"
  ASSESSRISKSANDNEEDS_BASEURL: "https://assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk"
  PRISONEROFFENDERSEARCH_BASEURL: "https://prisoner-offender-search-preprod.prison.service.justice.gov.uk"
  SENTRY_ENVIRONMENT: "preprod"
  AWS_S3_STORAGE_ENABLED: "true"
  AWS_S3_NDMIS_ENABLED: "true"
  OVERRIDES_SHOWFUTUREINTERVENTIONS: "true"
  FEATUREFLAGS_CURRENTLOCATION_ENABLED: "true"
  FEATUREFLAGS_SAVEPROBATIONPRACTITIONERDETAILS_ENABLED: "true"