# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/hmpps-interventions-service
  tag: latest
  ports:
    app: 8080
    dataDictionary: 8080

ingress:
  enabled: true
  hosts:
    - host: hmpps-interventions-service-preprod.apps.live-1.cloud-platform.service.justice.gov.uk

env:
  JAVA_OPTS: "-Xmx512m"
  HMPPSAUTH_BASEURL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
  INTERVENTIONSUI_BASEURL: "https://hmpps-interventions-ui-preprod.apps.live-1.cloud-platform.service.justice.gov.uk"
  COMMUNITYAPI_BASEURL: "https://community-api-secure.pre-prod.delius.probation.hmpps.dsd.io"
  COMMUNITYAPI_CONTACTNOTIFICATIONCONTEXT_PROVIDERCODE: "CRS"
  COMMUNITYAPI_CONTACTNOTIFICATIONCONTEXT_REFERRALTYPE: "CRS01"
  COMMUNITYAPI_CONTACTNOTIFICATIONCONTEXT_STAFFCODE: "CRSUATU"
  COMMUNITYAPI_CONTACTNOTIFICATIONCONTEXT_TEAMCODE: "CRSUAT"
