ALTER TABLE BATCH_STEP_EXECUTION ADD CREATE_TIME TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00';

ALTER TABLE BATCH_STEP_EXECUTION ALTER COLUMN START_TIME DROP NOT NULL;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN DATE_VAL;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN LONG_VAL;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN DOUBLE_VAL;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ALTER COLUMN TYPE_CD TYPE VARCHAR(100);

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS RENAME TYPE_CD TO PARAMETER_TYPE;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ALTER COLUMN KEY_NAME TYPE VARCHAR(100);

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS RENAME KEY_NAME TO PARAMETER_NAME;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ALTER COLUMN STRING_VAL TYPE VARCHAR(2500);

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS RENAME STRING_VAL TO PARAMETER_VALUE;

UPDATE METADATA SET COLUMN_NAME = 'parameter_type' WHERE COLUMN_NAME ='type_cd' and TABLE_NAME = 'batch_job_execution_params';

UPDATE METADATA SET COLUMN_NAME = 'parameter_name' WHERE COLUMN_NAME ='key_name' and TABLE_NAME = 'batch_job_execution_params';

UPDATE METADATA SET COLUMN_NAME = 'parameter_value' WHERE COLUMN_NAME ='string_val' and TABLE_NAME = 'batch_job_execution_params';

INSERT INTO METADATA (TABLE_NAME, COLUMN_NAME, SENSITIVE, DOMAIN_DATA) VALUES ('batch_step_execution','create_time',FALSE, FALSE);