INSERT INTO complexity_level (id, service_category_id, title, complexity, description)
-- DNR NE - Low & Medium
VALUES ('2160e538-87f2-408d-ba76-290a245dce19', '3c7ad8ff-86d9-4ba9-87c6-dc2d7b741240', 'Low complexity', 'LOW',
        'Person(s) on Probation who is highly motivated and has had sustained period of abstinence. Person(s) on Probation has successfully engaged in a period of treatment but requires support to sustain recovery.')
     , ('30460ce6-84b6-46f3-9f25-74f3371f5896', '3c7ad8ff-86d9-4ba9-87c6-dc2d7b741240', 'Medium complexity', 'MEDIUM',
        'Person(s) on Probations who has had lapses/crises that may lead to relapse and/or is at a transition point, e.g. from prison into community. Person(s) on Probation has a moderate level of motivation but requires a high level of support for dependencies linked to re-offending. Person(s) on Probations who are subject to a Community Sentence Treatment Requirement and need wraparound support to aid engagement. Person(s) on Probation does not meet the threshold for secondary provision treatment services and/or are deemed unsuitable following assessment for treatment as part of a Community Sentence Treatment Requirement.')
    ,  ('72a87fd8-49c0-4c9e-b460-94722488386e', '748732c2-7f94-4966-b5f2-d19e86e0cbf2', 'Low complexity', 'LOW',
        'Person(s) on Probation who is highly motivated and has had sustained period of abstinence. Person(s) on Probation has successfully engaged in a period of treatment but requires support to sustain recovery.')
     , ('43cac55c-df2c-4298-8fe2-8d303a86450b', '748732c2-7f94-4966-b5f2-d19e86e0cbf2', 'Medium complexity', 'MEDIUM',
        'Person(s) on Probations who has had lapses/crises that may lead to relapse and/or is at a transition point, e.g. from prison into community. Person(s) on Probation has a moderate level of motivation but requires a high level of support for dependencies linked to re-offending. Person(s) on Probations who are subject to a Community Sentence Treatment Requirement and need wraparound support to aid engagement. Person(s) on Probation does not meet the threshold for secondary provision treatment services and/or are deemed unsuitable following assessment for treatment as part of a Community Sentence Treatment Requirement.');