apiVersion: batch/v1
kind: CronJob
metadata:
  name: generate-ndmis-appointment-performance-report
spec:
  schedule: "5 19 * * FRI"
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.serviceAccountNameForNdmisReporting }}
          serviceAccountName: {{ .Values.serviceAccountNameForNdmisReporting }}
          {{- end }}
          restartPolicy: "Never"
          containers:
            - name: ndmis-appointment-performance-report
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: Always
              command: [ "java" ]
              args:
                - "-Xms2560m"
                - "-Xmx2560m"
                - "-XX:+AlwaysActAsServerClassMachine"
                - "-XX:+HeapDumpOnOutOfMemoryError"
                - "-XX:HeapDumpPath=/dumps"
                - "-javaagent:/app/agent.jar"
                - "-jar"
                - "/app/app.jar"
                - "--jobName=ndmisAppointmentPerformanceReportJob"
              resources:
                requests:
                  cpu: "1000m"
                  memory: "3Gi"
                limits:
                  cpu: "2"
                  memory: "4Gi"
              volumeMounts:
                - name: heap-dumps
                  mountPath: /dumps
  {{ include "deployment.envs" . | nindent 14 }}
          volumes:
            - name: heap-dumps
              emptyDir: {}
