apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}-api
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ template "app.name" . }}
                topologyKey: kubernetes.io/hostname
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.image.ports.app }}
              protocol: TCP
          volumeMounts:
          - name: heap-dumps
            mountPath: /dumps
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: {{ .Values.image.ports.app }}
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: {{ .Values.image.ports.app }}
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 10
  {{- include "deployment.envs" . | nindent 10 }}
      volumes:
        - name: heap-dumps
          emptyDir: {}
