apiVersion: batch/v1
kind: CronJob
metadata:
  name: conclude-referrals
spec:
  schedule: "30 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: conclude-referrals
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: Always
              args: ["--jobName=concludeReferralsJob"]
{{- include "deployment.envs" . | nindent 14 }}