apiVersion: batch/v1
kind: CronJob
metadata:
  name: rescheduled-reason
spec:
  schedule: "0 20 25 10 *"
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.serviceAccountName }}
          serviceAccountName: {{ .Values.serviceAccountName }}
          {{- end }}
          restartPolicy: "Never"
          containers:
            - name: rescheduled-reason
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: Always
              args: ["--jobName=rescheduledReasonJob"]
{{- include "deployment.envs" . | nindent 14 }}
