apiVersion: batch/v1
kind: CronJob
metadata:
  name: approve-action-plans
spec:
  schedule: "0 10 1 9 *"
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.serviceAccountName }}
          serviceAccountName: {{ .Values.serviceAccountName }}
          {{- end }}
          restartPolicy: "Never"
          containers:
            - name: approve-action-plans
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: Always
              args: ["--jobName=approveActionPlansJob"]
{{- include "deployment.envs" . | nindent 14 }}
