apiVersion: batch/v1
kind: CronJob
metadata:
  name: contract-onboarding
spec:
  schedule: "0 2 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: contract-onboarding
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: Always
              args: ["--jobName=upsertContractsJob"]
{{- include "deployment.envs" . | nindent 14 }}