apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-end-of-sentence
spec:
  schedule: "0 2 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: load-send-of-sentence
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: Always
              args: ["--jobName=loadEndOfSentenceJob"]
{{- include "deployment.envs" . | nindent 14 }}