apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-status
spec:
  schedule: "0 2 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: load-status
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: Always
              args: ["--jobName=loadStatusJob"]
{{- include "deployment.envs" . | nindent 14 }}