apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}-api
  labels:
    app: {{ template "app.name" . }}
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.image.ports.app }}
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}-dashboard
  labels:
    app: {{ template "app.name" . }}
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.image.ports.app }}
      name: http
  selector:
    {{- include "dashboardApp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}-performance-report
  labels:
    app: {{ template "app.name" . }}
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.image.ports.app }}
      name: http
  selector:
    {{- include "performanceReportApp.selectorLabels" . | nindent 4 }}
