apiVersion: v1
kind: Service
metadata:
  name: data-dictionary
  labels:
    app: data-dictionary
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.image.ports.dataDictionary }}
      name: http
  selector:
    {{- include "dataDictionary.selectorLabels" . | nindent 4 }}
