name: Build & push docker image and deploy to environment

on:
  workflow_call:
    inputs:
      environment:
        description: Environment
        required: true
        type: string
      app_version:
        description: App version
        required: true
        type: string
      k8s_deployment_name:
        description: Kubernetes deployment name
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      changelog_git_paths:
        description: Changelog git paths
        required: false
        default: ""
        type: string
      show_changelog:
        description: Show changelog
        default: true
        required: false
        type: boolean
      slack_notification:
        description: Slack notification
        default: "false"
        required: false
        type: string
      helm_additional_args:
        description: Helm additional args
        default: ""
        required: false
        type: string
      helm_timeout:
        description: Helm timeout
        default: "5m"
        required: false
        type: string
      helm_dir:
        description: Helm dir
        default: "helm_deploy"
        required: false
        type: string
      helm_chart_name:
        description: Name of the helm chart - defaults to the repo name
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      autogenerate_scheduled_downtime_cron:
        description: |
          Whether to autogenerate scheduled downtime cron values.
          For services that have enabled "scheduledDowntime".
          This will override the "startup" and "shutdown" cron values and set them during Helm install/upgrade.
          Ensures startups and shutdowns are randomly spaced out to avoid cluster scheduling issues.
          Startup times are between 6am-7am. Shutdown times are between 9pm-10pm.
        required: false
        default: true
        type: boolean

permissions:
  contents: read

jobs:

  deploy_env:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: azure/setup-kubectl@v4
        id: install
        with:
          version: latest

      - name: Set Slack Channel ID
        id: set-slack-channel-id
        run: |
          if [[ "${{ inputs.environment }}" == "prod" || "${{ inputs.environment }}" == "production" ]]; then
            echo "slack_channel_id=${{ vars.PROD_RELEASES_SLACK_CHANNEL }}" | tee -a $GITHUB_OUTPUT
          else
            echo "slack_channel_id=${{ vars.NONPROD_RELEASES_SLACK_CHANNEL }}" | tee -a $GITHUB_OUTPUT
          fi

      - uses: ./.github/actions/cloud-platform-deploy # INTERNAL_WORKFLOW
        id: deploy
        with:
          environment: ${{ inputs.environment }}
          version: ${{ inputs.app_version }}
          api: https://${{ secrets.KUBE_CLUSTER }}
          cert: ${{ secrets.KUBE_CERT }}
          cluster: ${{ secrets.KUBE_CLUSTER }}
          namespace: ${{ secrets.KUBE_NAMESPACE }}
          token: ${{ secrets.KUBE_TOKEN }}
          k8s_deployment_name: ${{ inputs.k8s_deployment_name }}
          changelog_git_paths: ${{ inputs.changelog_git_paths }}
          show_changelog: ${{ inputs.show_changelog }}
          helm_additional_args: ${{ inputs.helm_additional_args }}
          helm_timeout: ${{ inputs.helm_timeout }}
          helm_dir: ${{ inputs.helm_dir }}
          helm_chart_name: ${{ inputs.helm_chart_name }}
          helm_allowlist_groups: ${{ vars.HMPPS_IP_ALLOWLIST_GROUPS_YAML }}
          helm_allowlist_version: ${{ vars.HMPPS_IP_ALLOWLIST_GROUPS_VERSION }}
          autogenerate_scheduled_downtime_cron: ${{inputs.autogenerate_scheduled_downtime_cron }}

      # Notification bit - always send prod releases to dps-releases - CVA3MKDTR
      - if: ${{ always() && ( inputs.environment == 'prod' || inputs.environment == 'production' ) }}
        id: prod-dps-slack
        uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_release_results@v2
        with:
          channel_id: 'CVA3MKDTR'
          environment: ${{ inputs.environment }}
          app_version: ${{ inputs.app_version }}
          deploy_outcome: ${{ steps.deploy.outcome }}
          slack_bot_token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
          deployment_changelog: ${{ steps.deploy.outputs.deployment_changelog }}
          k8s_deployment_name: ${{ inputs.k8s_deployment_name }}

      # Optional prod releases slack channel (using PROD_RELEASES_SLACK_CHANNEL variable)
      - if: ${{ always() && ( inputs.slack_notification == 'true' && steps.set-slack-channel-id.outputs.slack_channel_id != '' ) }}
        id: send-release-slack
        uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_release_results@v2
        with:
          channel_id: ${{ steps.set-slack-channel-id.outputs.slack_channel_id }}
          environment: ${{ inputs.environment }}
          app_version: ${{ inputs.app_version }}
          deploy_outcome: ${{ steps.deploy.outcome }}
          slack_bot_token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
          deployment_changelog: ${{ steps.deploy.outputs.deployment_changelog }}
          k8s_deployment_name: ${{ inputs.k8s_deployment_name }}