name: Nightly

on:
  schedule:
    - cron: '0 7 * * 1-5' # 7 AM Monday-Friday
  workflow_dispatch:
permissions:
  contents: read
  packages: write
env:
  PACT_BROKER_BASE_URL: 'https://pact-broker-prod.apps.live-1.cloud-platform.service.justice.gov.uk'
  PACT_BROKER_USERNAME: 'interventions'
concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: true
jobs:
  veracode_policy_scan:
    name: Veracode Policy Scan
    uses: ./.github/workflows/security_veracode_policy_scan.yml
    secrets: inherit
  trivy_latest_scan:
    name: Trivy Latest Scan
    uses: ./.github/workflows/security_trivy.yml
    secrets: inherit
  gradle_owasp_dependency_check:
    name: Owasp Security Check
    uses: ./.github/workflows/security_owasp.yml
    secrets: inherit
