name: Nightly

on:
  schedule:
    - cron: '0 7 * * 1-5' # 7 AM Monday-Friday
  workflow_dispatch:
permissions:
  contents: read
  packages: write
  actions: read
  security-events: write
concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: true
jobs:
  veracode_policy_scan:
    name: Veracode Policy Scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_policy_scan.yml@v2
    secrets: inherit
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
  trivy_latest_scan:
    name: Trivy Latest Scan
    needs: veracode_policy_scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@v2
    secrets: inherit
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
  owasp_dependency_check:
    name: OWASP dependency check
    needs: trivy_latest_scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_owasp.yml@v2
    secrets: inherit
    with:
      nvd_feed_version: '2'
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
