name: Security OWASP dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "43 9 * * MON-FRI" # Every weekday at 09:43 UTC
jobs:
  security-kotlin-owasp-check:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Kotlin security OWASP dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_owasp.yml@v2
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      nvd_feed_version: '2'
    secrets: inherit
